# Generated by Django 2.1.1 on 2018-11-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active_status', models.BooleanField(default=True)),
                ('positions', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ArticleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='articles.Article')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_items', to='shop.Product')),
            ],
        ),
    ]
