# Generated by Django 2.1.1 on 2018-11-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181125_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('created',), 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
