# Generated by Django 2.1.1 on 2018-11-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181125_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
    ]
